### ISSUE TITLE
Error extracts the context from the HTTP headers

### ISSUE THREAD

**Issue by doanthai** [openzipkin/zipkin-php#137] opened 2020-04-13 12:12 UTC
I see a problem with your code that extractor can't extracts the context from the HTTP headers if headers key contain upper case. In my code I use array_change_key_case function to change all key of header to lowercase. I hope you will fix it in next version.

**Comment by jcchavezs** [comment] 2020-04-13 12:24
I remember using lower case for avoiding iterating over the whole headers
array. Could you open a PR with a failing test case and potentially the fix
(against V1 branch)? Otherwise, maybe copy some code showing the error?

**Comment by doanthai** [comment] 2020-04-13 13:04
You can run this code or run it on your local and check my result. With code from your example, extractor function return DefaultSamplingFlags object that mean it will not receive traceId from header.

> <?php

use Zipkin\Propagation\Map;

require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/functions.php';

$tracing = create_tracing('backend', '127.0.0.2');

$carrier = array(
    "X-b3-traceid" => "68dcf7b0a26fc4cf",
    "X-b3-spanid" => "7ea49b3e6e536962",
    "X-b3-parentspanid" => "68dcf7b0a26fc4cf",
    "X-b3-sampled" => "1",
    "-b3-flags" => "0"
);

/* Extracts the context from the HTTP headers */
$extractor = $tracing->getPropagation()->getExtractor(new Map());
$extractedContext = $extractor($carrier);
$extractedContextLowerCase = $extractor(array_change_key_case($carrier,CASE_LOWER));


var_dump($extractedContextLowerCase);
var_dump($extractedContext);

//Result 
// object(Zipkin\Propagation\TraceContext)#17 (6) {
//     ["isSampled":"Zipkin\Propagation\TraceContext":private]=>
//     bool(true)
//     ["isDebug":"Zipkin\Propagation\TraceContext":private]=>
//     bool(false)
//     ["traceId":"Zipkin\Propagation\TraceContext":private]=>
//     string(16) "68dcf7b0a26fc4cf"
//     ["spanId":"Zipkin\Propagation\TraceContext":private]=>
//     string(16) "7ea49b3e6e536962"
//     ["parentId":"Zipkin\Propagation\TraceContext":private]=>
//     string(16) "68dcf7b0a26fc4cf"
//     ["usesTraceId128bits":"Zipkin\Propagation\TraceContext":private]=>
//     bool(false)
//   }
//   object(Zipkin\Propagation\DefaultSamplingFlags)#9 (2) {
//     ["isSampled":"Zipkin\Propagation\DefaultSamplingFlags":private]=>
//     NULL
//     ["isDebug":"Zipkin\Propagation\DefaultSamplingFlags":private]=>
//     bool(false)
//   }

**Comment by jcchavezs** [comment] 2020-04-19 21:52
Hi @doanthai, sorry for not coming back earlier. I think what you are experiencing is cumbersome combination of issues.

First, you seem to be trying to parse http headers using the `Map` getter. That is legit and a common use case, mostly because frameworks and libraries like symfony still don't use the PSR request/response objects (i.e. the official ones), thus `Request` getter can't be used and map is the way to go (e.g. https://github.com/jcchavezs/zipkin-instrumentation-symfony/blob/master/src/ZipkinBundle/Middleware.php#L60).

Main thing with `Map` is that it is not supposed to be key case insensitive, however when we write into a map, we use lowercase key (see https://github.com/openzipkin/zipkin-php/blob/master/src/Zipkin/Propagation/Map.php#L42) and when we get we also use the the lower case key (see https://github.com/openzipkin/zipkin-php/blob/master/src/Zipkin/Propagation/Map.php#L19). This is mainly to fulfill the use case described in the previous paragraph.

What you propose would work for array and hence most of the use cases, however it is the `ArrayAccess` what concerns me. It is not an iterable so we can't access to the keys and thus the only option is to keep this case insensitiviness for the array case (the most common one). Not sure how common the `ArrayAccess` case it is, it is very likely I added support for ArrayAccess just because "I could",  increasing the surface of this API unnecessarily but it is too late to break the contract now and remove for it. Maybe for v2 (cc @adriancole)?

Anyways I will prepare a fix for the array case.

**Comment by jcchavezs** [comment] 2020-04-24 10:57
The issue is fixed now. You can use the version https://github.com/openzipkin/zipkin-php/releases/tag/1.3.5 now.

**Closed** 2020-04-24 10:56 UTC
